{% set name = "aioserial" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3fe60dbb7b4777c9467deb044c0b05fa7f27e602775578dee07fd215df335cbc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python 

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pyserial
    - python >=3.6

test:
  imports:
    - aioserial

about:
  home: http://github.com/changyuheng/aioserial
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: 'pyserial-asyncio for humans'
  doc_url: https://github.com/changyuheng/aioserial 
  dev_url: https://github.com/changyuheng/aioserial 

extra:
  recipe-maintainers:
    - Benjamin-Lee
