travis:
  secure:
    BINSTAR_TOKEN: xERnAmREevNHT+H/2K7fUz8mXUcVc8Rrw+C2OXZzw3mazjEj+ZpJ5T3we5u/tQv4XOSlES6Ya3OfhxVRz2b965ay4I35IxyVCngH+znb6rRcBir+aBaWJWdZRf03jfuvAaby9j9r7BpQ351GS3B+aKKudlZCihJlnpL87QLIDKG0UTpZU7okdeaq874F2NFOOZWgGhvu4sTNxkoAAvz3xL5/qfYIvsBbbMwBBXEGOZQvGStJ35Bb9DWC3XD7Lts9Wfw7a+JiFQbyvyFlSrIVUFHHIJXrK+Ih6ZiZV9mgvBBwR6l+hbjt1Bk6Gisa7VjjuotRH72BhWOhuPGNqhDJPdDsUbIbrfCIcAhrsbhIgZgI1zMQJXK4sYJLlq1aSolYbX1aJVJed9kCBft35SThfeYL0r7h0FJlruYAt5LmwPDR+Mm9xq3di9aIFdcgGXScTIib+/CPHSmMoeGVr0cYQIMT1FVFUTbBisgI6eRCUW/Es9oYq7fskEUFc3Mt8jumx4X81OeYqCMMVKPzrZuJmlX0x9jPqFMwkla8g/Iw2bW8Ornl6/EOMROuEyl0vw6KAjgJ+kgKBgcyum7odzs4UI6ZTlB6nTS5BCQ53FBA1vu4E3mhuhXeWH+7HLFqUIOcZiSnv47QZ5EVPJQHBYdD5trOFVBO+D9M38snnIpfMiw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
